#! /usr/bin/ruby -E:UTF-8
# -*- mode:Ruby; tab-width:4; coding:UTF-8; -*-
# vi:set ft=ruby ts=4 fenc=UTF-8 :
#----------------------------------------------------------------
# DVD IFO VOBをmp4に変換する
#
# 2020/06/14 opa⁠🙂
#----------------------------------------------------------------
ProgName = "dvd2mp4"
Version = "1.04"
#=====dpk===== Copyright2020
Copyright = "Copyright (c) 2020 by opa"
#=====dpk=====
FFMPEG_CMD = "ffmpeg"
FFPROBE_CMD = "ffprobe"
LSDVD_CMD = "lsdvd"

LANGTABLE = {
	"ja" => "jpn",
	"en" => "eng",
	"fr" => "fra",
	"xx" => nil,
}

FF_ANALYZEDURATION = "600M" # 10min
FF_PROBESIZE = "450M" # 450MB

require 'optparse'
require 'open3'
require 'json'
require 'tempfile'
require 'shellwords'
require 'pp'

def var_init
	$PROGRAM_NAME = ProgName
	$metadata = {}
	$rcode = 0
end

def myShellwordsJoin_q(s)
	if s =~ /[\s;&()|^<>?*\[\]$`"\\!{}]/
		return "'" + s.gsub("'") { "'\\''" } + "'"
	else
		return s.gsub("'") { "\\'" }
	end
end

def myShellwordsJoin(args)
	return args.map { |a|
		(a =~ /^(--.+=)(.*)$/) ? myShellwordsJoin_q($1) + myShellwordsJoin_q($2) : myShellwordsJoin_q(a)
	}.join(" ")
end

def sec2hhmmss(sec, full:false)
	r = ""
	d, m = sec.divmod(1) # 秒以下
	r = sprintf(".%03d", (m * 1000).round)  if m != 0 || full
	d, m = d.divmod(60) # 秒
	r = sprintf("%02d", m) + r
	if d > 0 || full
		d, m = d.divmod(60) # 分
		r = sprintf("%02d:", m) + r
	end
	if d > 0 || full
		d, m = d.divmod(60) # 時
		r = sprintf("%02d:", m) + r
	end
	return r
end

def pos2sec(pos, fr=nil) # Rational(30000,1001)
	case pos
	when /^([+-]?\d+)f$/
		return $1.to_f / fr
	when /^(\d+):(\d+):(\d+(?:\.\d*)?)$/
		return $1.to_i * 3600 + $2.to_i * 60 + $3.to_f
	when /^(\d+):(\d+(?:\.\d*)?)$/
		return $1.to_i * 60 + $2.to_f
	when /^([+-]?\d+(?:\.\d*)?s?)$/
		return $1.to_f
	else
		fail "位置の指定が不正です: #{pos}"
	end
end

def vts_num_to_i(vts_num)
	case vts_num
	when /^VTS_(\d+)$/i, /^v(\d+)$/i
		i = $1.to_i
	else
		fail "'VTS_n'の形式で指定してください"
	end
	return i
end

def guess_lang(s)
	case s
	when /(英語|English)/i
		return "eng"
	when /(日本語|Japanese)/i
		return "jpn"
	end

	return nil
end

def get_vobfiles(vts_num)
	if vts_num >= 1
		vobfiles = Dir.glob(sprintf("VTS_%02d_*.VOB", vts_num), File::FNM_CASEFOLD).sort
		vobfiles.shift  if vobfiles.size >= 2 && vobfiles.first =~ /^VTS_\d+_0\.VOB/i
		fail "入力VOBファイルがひとつもありません"  if vobfiles.empty?
		ifofiles = Dir.glob(sprintf("VTS_%02d_*.IFO", vts_num), File::FNM_CASEFOLD).sort
	elsif vts_num == 0
		vobfiles = Dir.glob("VIDEO_TS.VOB", File::FNM_CASEFOLD).sort
		fail "VIDEO_TS.VOBがありません"  if vobfiles.empty?
		ifofiles = Dir.glob("VIDEO_TS.IFO", File::FNM_CASEFOLD).sort
	end
	return [vobfiles, ifofiles]
end

def probe_disc_data_raw
	if !File.exist?("VIDEO_TS.IFO")
		fail "DVDのインデックスファイルが存在しません"
	end

	cmd = [LSDVD_CMD]
	cmd += ["-x"]
	cmd += ["-Or", "."]
	r = Open3.capture3(*cmd)

	if r[0].empty?
		printf("%s\n", r[1])
		fail "lsdvdの実行に失敗しました"
	end

	return eval(r[0])
end

def probe_disc_data
	pd = probe_disc_data_raw

	pd[:track].each.with_index(1) do |title, ix|
		fail "lsdvdのタイトル情報に飛び番があります"  if title[:ix] != ix
		# TODO : アングル情報のチェック
		title[:audio].each.with_index(1) do |audio, ix|
			fail "lsdvdのオーディオ情報に飛び番があります"  if audio[:ix] != ix
		end
		title[:chapter].each.with_index(1) do |chapter, ix|
			fail "lsdvdのチャプター情報に飛び番があります"  if chapter[:ix] != ix
		end
		title[:cell].each.with_index(1) do |cell, ix|
			fail "lsdvdのセル情報に飛び番があります"  if cell[:ix] != ix
		end
		title[:subp].each.with_index(1) do |subp, ix|
			fail "lsdvdの字幕情報に飛び番があります"  if subp[:ix] != ix
		end
	end

	vts_wk = {}
	pd[:track].each do |title|
		vts_wk[title[:vts]] ||= []
		vts_wk[title[:vts]] << title
	end
	vts = []
	vts_wk.each do |v, t|
		vts << {vts:v, titles:t}
	end
	vts.sort_by! { |v| v[:vts] }
	vts.each.with_index(1) do |vts, ix|
		fail "使われているVTS番号に飛び番があります"  if vts[:vts] != ix
	end
	pd[:vts] = vts

	if $adjust_fps
		adjust_fps_factor = Rational(30000,1000) / Rational(30000,1001)
		pd[:track].each do |title|
			title[:length] *= adjust_fps_factor
			title[:chapter].each do |chapter|
				chapter[:length] *= adjust_fps_factor
			end
			title[:cell].each do |cell|
				cell[:length] *= adjust_fps_factor
			end
		end
	end

	return pd
end

def probe_vts_data_raw(vts_num)
	vobfiles, ifofiles = get_vobfiles(vts_num)

	cmd1 = ["cat"]
	cmd1 += vobfiles

	cmd2 = [FFPROBE_CMD]
	cmd2 += ["-hide_banner"]
	cmd2 += ["-loglevel", "warning"]
	cmd2 += ["-analyzeduration", FF_ANALYZEDURATION]
	cmd2 += ["-probesize", FF_PROBESIZE]
	cmd2 += ["-print_format", "json"]
	cmd2 += ["-show_format"]
	cmd2 += ["-show_streams"]
	cmd2 += ["-i", "-"]
	return JSON.parse(Open3.pipeline_r(cmd1, cmd2)[0].read, symbolize_names:true)
end

def probe_vts_data(vts_num)
	disc = probe_disc_data
	if vts_num >= 1
		if !disc[:vts][vts_num - 1]
			fail sprintf("VTS_%02dの情報はありません", vts_num)
		end
		titles = disc[:vts][vts_num - 1][:titles]
	else
		titles = []
	end

	# ストリーム情報の取得
	vobfiles, ifofiles = get_vobfiles(vts_num)

	cmd1 = ["cat"]
	cmd1 += vobfiles

	cmd2 = [FFPROBE_CMD]
	cmd2 += ["-hide_banner"]
	cmd2 += ["-loglevel", "error"]
	cmd2 += ["-analyzeduration", FF_ANALYZEDURATION]
	cmd2 += ["-probesize", FF_PROBESIZE]
	cmd2 += ["-print_format", "json"]
	cmd2 += ["-show_format"]
	cmd2 += ["-show_streams"]
	cmd2 += ["-i", "-"]
	ffprobe = JSON.parse(Open3.pipeline_r(cmd1, cmd2)[0].read, symbolize_names:true)

	streams = ffprobe[:streams]
	streams_v = []
	streams_a = []
	streams_s = []
	streamids = {}
	streams.each.with_index(1) do |stream, ix|
		fail "ffprobeでのストリーム番号に飛び番があります"  if stream[:index] != ix-1
		stream[:ix] = ix
		fail "ffprobeでのストリームIDに重複があります"  if streamids.include?(stream[:id].to_i(0))
		streamids[stream[:id].to_i(0)] = true

		case stream[:codec_type]
		when "video"
			streams_v << stream
		when "audio"
			streams_a << stream

			streamid = stream[:id].to_i(0)
			lsdvd = nil
			titles.each do |title|
				title[:audio].each do |audio|
					if audio[:streamid].to_i(0) == streamid
						lsdvd = audio
						break
					end
				end
				break  if lsdvd
			end
			if lsdvd
				stream[:langcode] = lsdvd[:langcode]
				stream[:language] = lsdvd[:language]
				stream[:content] = lsdvd[:content]
				stream[:lang] = LANGTABLE[stream[:langcode]]
				fail sprintf("言語コードが変換できません: %s", stream[:langcode])  if !LANGTABLE.include?(stream[:langcode])
			end
		when "subtitle"
			streams_s << stream

			streamid = stream[:id].to_i(0)
			lsdvd = nil
			titles.each do |title|
				title[:subp].each do |subp|
					if subp[:streamid].to_i(0) == streamid
						lsdvd = subp
						break
					end
				end
				break  if lsdvd
			end
			if lsdvd
				stream[:langcode] = lsdvd[:langcode]
				stream[:language] = lsdvd[:language]
				stream[:content] = lsdvd[:content]
				stream[:lang] = LANGTABLE[stream[:langcode]]
				fail sprintf("言語コードが変換できません: %s", stream[:langcode])  if !LANGTABLE.include?(stream[:langcode])
			end
		when "data"
			# NOP
		else
			fail "不明なcodec_typeです: #{stream[:codec_type]}"
		end
	end

	# セル一覧を作成
	cells = []
	ctmap = {0 => 0.0}
	titles.each do |title|
		title[:cell].each do |cell|
			if !cells.find { |c|
				c[:first_sector] == cell[:first_sector] &&
				c[:last_sector] == cell[:last_sector]
			}
				cells << {
					ix: nil,
					start: nil,
					end: nil,
					length: cell[:length],
					first_sector: cell[:first_sector],
					last_sector: cell[:last_sector],
				}
			end
		end
	end
	cells.sort_by! { |c| c[:first_sector] }
	# 先頭から順に開始位置と終了位置を特定
	cells.each.with_index(1) do |cell, ix|
		startsec = ctmap[cell[:first_sector]]
		if !startsec
			startsec = ctmap.max[1]
			ctmap[cell[:first_sector]] = startsec
			printf("セル情報が不連続のため、開始時刻を確定できません\n")
		end
		endsec = startsec + cell[:length]

		cell[:ix] = ix
		cell[:start] = startsec
		ctmap[cell[:last_sector] + 1] = endsec
		cell[:end] = endsec
	end

	# chapter_offset を算出
	framerate = Rational(streams_v.first[:avg_frame_rate])
	chapter_offset = $chapter_offset ? pos2sec($chapter_offset, framerate) : 0

	# チャプター一覧を作成
	chapters = []
	titles.each do |title|
		title[:chapter].each do |chapter|
			cell = title[:cell][chapter[:startcell]-1]
			if !chapters.find { |c|
				c[:length] == chapter[:length] &&
				c[:first_sector] == cell[:first_sector]
			}
				chapters << {
					ix: nil,
					title_ix_in_vts: title[:ix],
					chapter_ix_in_title: chapter[:ix],
					start: nil,
					end: nil,
					length: chapter[:length],
					first_sector: cell[:first_sector],
				}
			end
		end
	end
	chapters.sort_by! { |c| c[:first_sector] }
	# チャプター開始位置,終了位置を決定
	chapters.each.with_index(1) do |chapter, ix|
		startsec = ctmap[chapter[:first_sector]]
		fail "チャプター開始時刻を確定できません"  if !startsec
		endsec = startsec + chapter[:length]

		startsec += chapter_offset
		startsec = 0  if startsec < 0
		endsec += chapter_offset
		endsec = 0  if endsec < 0
		length = endsec - startsec

		chapter[:ix] = ix
		chapter[:start] = startsec
		chapter[:end] = endsec
		chapter[:length] = length
	end
	# 次のチャプターを突き抜けてしまっているチャプターを調整
	chapters.each_with_index do |chapter, i|
		next_chapter = chapters[i+1]
		break  if !next_chapter

		if chapter[:end] > next_chapter[:start]
			chapter[:end] = next_chapter[:start]
			chapter[:length] = chapter[:end] - chapter[:start]
		end
	end
	# 指定長より短いチャプターを削除
	prev_chapter = nil
	chapters.each do |chapter|
		if prev_chapter && chapter[:length] < $delete_chpt_sec
			prev_chapter[:length] += chapter[:length]
			prev_chapter[:end] += chapter[:length]
			chapter[:start] += chapter[:length]
			chapter[:length] = 0
		else
			prev_chapter = chapter
		end
	end
	# 長さ0のチャプターを削除
	chapters.delete_if { |c| c[:length] == 0 }

	return {
		disc: disc,
		vts_num: vts_num,
		titles: titles,
		chapters: chapters,
		vobfiles: vobfiles,
		ifofiles: ifofiles,
		format: ffprobe[:format],
		streams: streams,
		streams_v: streams_v,
		streams_a: streams_a,
		streams_s: streams_s,
	}
end

def measure_vob_duration(vts_num)
	vobfiles, = get_vobfiles(vts_num)

	vobtime = 0
	vobfiles.each do |vobfile|
		cmd = [FFPROBE_CMD]
		cmd += ["-hide_banner"]
		cmd += ["-loglevel", "warning"]
		cmd += ["-print_format", "json"]
		cmd += ["-show_format"]
		cmd += ["-i", vobfile]
		r = Open3.capture3(*cmd)
		ffprobe = JSON.parse(r[0], symbolize_names:true)
		vobtime += ffprobe[:format][:duration].to_f
	end

	return vobtime
end

def measure_strict_duration(vts_num)
	printf("Measuring strict VTS duration...\n")

	vobfiles, = get_vobfiles(vts_num)
	wfile = Tempfile.new(["vtsmeasure", ".wav"])

	cmd1 = ["cat"]
	cmd1 += vobfiles

	cmd2 = [FFMPEG_CMD]
	cmd2 += ["-hide_banner"]
	cmd2 += ["-loglevel", "error"]
	cmd2 += ["-y"]
	cmd2 += ["-i", "-"]
	cmd2 += ["-f", "wav"]
	cmd2 += ["-ac", "1"] # モノラル
	cmd2 += ["-codec:a", "pcm_u8"]
	cmd2 += [wfile.path]
	Open3.pipeline(cmd1, cmd2)

	cmd3 = [FFPROBE_CMD]
	cmd3 += ["-hide_banner"]
	cmd3 += ["-loglevel", "warning"]
	cmd3 += ["-print_format", "json"]
	cmd3 += ["-show_format"]
	cmd3 += ["-i", wfile.path]
	ffprobe = JSON.parse(Open3.capture3(*cmd3)[0], symbolize_names:true)

	return ffprobe[:format][:duration].to_f
end

def probe_disc
	pd = probe_disc_data

	printf("disc title : %s\n", pd[:title])  if pd[:title] != "unknown"
	printf("vmg_id : %s\n", pd[:vmg_id])  if pd[:vmg_id] != "DVDVIDEO-VMG"
	printf("provider id : %s\n", pd[:provider_id])  if pd[:provider_id] != ""

	pd[:vts].each do |vts|
		printf("VTS_%02d :", vts[:vts])
		vts[:titles].each_with_index do |title, i|
			if i == 0
				printf(" %dx%d(%s) %0.2ffps", title[:width], title[:height], title[:aspect], title[:fps])
			else
				print("                               ")
			end
			printf(" Title %d %s(%0.1fs)", title[:ix], sec2hhmmss(title[:length], full:true), title[:length])
			aux = ""
			aux += sprintf(" angle:%d", title[:angles])  if title[:angles] != 1
			aux += sprintf(" audio:%d", title[:audio].size)  if title[:audio].size != 1
			aux += sprintf(" subt:%d", title[:subp].size)  if title[:subp].size != 0
			aux += sprintf(" chpt:%d", title[:chapter].size)  if title[:chapter].size != 1
			aux += sprintf(" longest")  if title[:ix] == pd[:longest_track]
			print(" /" + aux)  if !aux.empty?
			print("\n")
		end
	end
end

def probe_vts(vts_num)
	pd = probe_vts_data(vts_num)

	if $strict_length
		video_duration = measure_strict_duration(vts_num)
	else
		video_duration = measure_vob_duration(vts_num)
	end

	printf("VTS_%02d :", vts_num)

	if pd[:streams_v].size != 1
		fail "想定外のビデオストリーム数: #{pd[:streams_v].size}"
	end

	video = pd[:streams_v].first
	printf(" %dx%d(%s)", video[:width], video[:height], video[:display_aspect_ratio])
	printf(" %0.2ffps", Rational(video[:avg_frame_rate]).to_f)
	printf(" %s", video[:field_order])
	printf(" %s(%0.3fs)", sec2hhmmss(video_duration, full:true), video_duration)

	aux = ""
	#aux += sprintf(" angle:%d", pd[:angles])  if track[:angles] != 1
	aux += sprintf(" audio:%d", pd[:streams_a].size)  if pd[:streams_a].size != 1
	aux += sprintf(" subt:%d", pd[:streams_s].size)  if pd[:streams_s].size != 0
	aux += sprintf(" chpt:%d", pd[:chapters].size)  if pd[:chapters].size != 1
	print(" /" + aux)  if !aux.empty?
	print("\n")

	pd[:disc][:track].each do |title|
		next  if title[:vts] != vts_num
		if title[:angles] != 1
			printf("Angle %d :", 1)
			print(" 複数アングルがあります\n")
		end
	end

	pd[:streams_a].each.with_index(1) do |audio, ix|
		printf("Audio %d :", ix)
		printf(" %s %s %dHz %dch", audio[:language], audio[:codec_long_name], audio[:sample_rate], audio[:channels])
		printf(" %s", audio[:content])  if audio[:content] && !audio[:content].empty? && audio[:content] != "Undefined"
		print("\n")
	end

	pd[:streams_s].each.with_index(1) do |subp, ix|
		printf("Subtitle %d :", ix)
		printf(" %s", subp[:language])
		printf(" %s", subp[:content])  if subp[:content] && !subp[:content].empty? && subp[:content] != "Undefined"
		print("\n")
	end

	pd[:chapters].each.with_index(1) do |chapter, ix|
		printf("Chapter %d :", ix)
		printf(" %s - %s %s(%0.3fs)", sec2hhmmss(chapter[:start], full:true), sec2hhmmss(chapter[:end], full:true),
		 							sec2hhmmss(chapter[:length]), chapter[:length])
		print("\n")
	end

	pd[:disc][:track].each do |title|
		next  if title[:vts] != vts_num

		if title[:angles] > pd[:streams_v].size
			printf("タイトル%dのアングルは%d個ですが、ビデオストリームは%d個しかありません\n",
				title[:ix], title[:angles], pd[:streams_v].size)
		end
		if title[:audio].size > pd[:streams_a].size
			printf("タイトル%dのオーディオチャネルは%d個ですが、オーディオストリームは%d個しかありません\n",
				title[:ix], title[:audio].size, pd[:streams_a].size)
		end
		if title[:subp].size > pd[:streams_s].size
			printf("タイトル%dの字幕数は%d個ですが、字幕ストリームは%d個しかありません\n",
				title[:ix], title[:subp].size, pd[:streams_s].size)
		end
	end
end

def dvd2mp4(vts_num)
	pd = probe_vts_data(vts_num)
	vs1 = pd[:streams_v].first
	framerate = Rational(vs1[:avg_frame_rate])
	vts_begin_sec = pd[:chapters].map{ |c| c[:start] }.min
	vts_end_sec = pd[:chapters].map{ |c| c[:end] }.max
	output_ranges = []

	# 開始:終了位置を決定
	start_offset = $start_pos ? pos2sec($start_pos, framerate) : vts_begin_sec
	end_offset = $end_pos ? pos2sec($end_pos, framerate) : vts_end_sec
	end_offset = start_offset + pos2sec($duration, framerate)  if $duration
	end_offset = start_offset  if end_offset < start_offset

	# 出力範囲がなにも指定されていない場合、# 最初から最後までを1つの塊で出力
	if !$output_chapters && !$output_ranges
		output_ranges << (vts_begin_sec .. vts_end_sec)
	end

	# チャプター単位の出力範囲が指定されている場合
	if $output_chapters
		if $output_chapters.empty? # 最初から最後までをチャプター毎にバラバラで出力
			pd[:chapters].each do |chapter|
				output_ranges << (chapter[:start] .. chapter[:end])
			end
		else # 指定されたとおりに出力
			$output_chapters.each do |oc|
				if oc.is_a?(Range)
					b = oc.begin
					e = oc.end
				else
					b = e = oc
				end
				# チャプター番号を上限下限におさめる
				b = b.clamp(0, pd[:chapters].length-1)
				e = e.clamp(0, pd[:chapters].length-1)
				# チャプター番号から秒へ変換
				b = pd[:chapters][b][:start]
				e = pd[:chapters][e][:end]
				output_ranges << (b .. e)
			end
		end
	end

	# 秒単位の出力範囲が指定されている場合
	if $output_ranges
		$output_ranges.each do |range|
			if range =~ /^(.*)-(.*)$/
				b = pos2sec($1, framerate)
				e = pos2sec($2, framerate)
			else
				b = pos2sec(range, framerate)
				e = vts_end_sec
			end
			b = b.clamp(vts_begin_sec, vts_end_sec)
			e = e.clamp(vts_begin_sec, vts_end_sec)
			output_ranges << (b .. e)
		end
	end

	# 開始時刻順に並べ替え
	output_ranges.sort_by! { |r| r.begin }

	# 次の出力範囲を突き抜けてしまっているものを調整
	r_limit = vts_end_sec
	work_ranges = []
	output_ranges.reverse_each do |r|
		work_ranges << (r.begin .. (r.end > r_limit ? r_limit : r.end))
		r_limit = r.begin
	end
	work_ranges.sort_by! { |r| r.begin }
	output_ranges.replace(work_ranges)

	# 開始:終了位置のオフセット調整
	output_ranges.map! do |r|
		b = r.begin + start_offset
		if b > r.end
			b = r.end
		end
		e = r.end
		if (r.end - r.begin) > end_offset
			e = r.begin + end_offset
		end
		if e < b
			e = b
		end
		(b .. e)
	end

	# 長さ0の範囲を削除
	output_ranges.delete_if { |r| r.begin >= r.end }

	if output_ranges.length < 1
		fail "出力対象範囲が指定されていません"
	end

	# ファイルのメタ情報を決定
	if !$metadata[:album_name]
		if pd[:disc][:title] && pd[:disc][:title] != "unknown"
			$stdout.printf("アルバム名をディスク情報から取得します: %s\n", pd[:disc][:title])
			$metadata[:album_name] = pd[:disc][:title]
		end
	end

	if !$metadata[:title_name]
		$stdout.printf("タイトルが指定されていません\n")
	end

	# 出力ファイル名のベース部分を生成
	if $metadata[:title_name]
		if $metadata[:title_num]
			dst_basename = "#{$metadata[:title_num]} #{$metadata[:title_name]}".strip
		else
			dst_basename = "#{$metadata[:title_name]}"
		end
	else
		dst_basename = sprintf("VTS_%02d", vts_num)
	end
	if $testmode
		dst_basename = "(test)" + dst_basename
	end

	# ストリームのメタ情報を決定
	pd[:streams_v].each_with_index do |stream, ix|
		title = $metadata[:s_video_name][ix]
		# if !title
		# 	$stdout.printf("ビデオストリーム #{ix+1} のタイトルが指定されていません\n")
		# 	title = "#{stream[:codec_long_name]} #{stream[:width]}x#{stream[:height]} #{stream[:display_aspect_ratio]}".strip
		# end
		stream[:title] = title
	end

	pd[:streams_a].each_with_index do |stream, ix|
		title = $metadata[:s_audio_name][ix]
		if !title
			$stdout.printf("オーディオストリーム #{ix+1} のタイトルが指定されていません\n")
			if stream[:lang]
				title = "#{stream[:language]} #{stream[:channel_layout]}".strip
			else
				title = "#{stream[:channel_layout]}".strip
			end
		else
			if !stream[:lang]
				stream[:lang] = guess_lang(title)
			end
		end
		stream[:title] = title
	end

	pd[:streams_s].each_with_index do |stream, ix|
		title = $metadata[:s_subtitle_name][ix]
		if !title
			$stdout.printf("字幕ストリーム #{ix+1} のタイトルが指定されていません\n")
			title = "#{stream[:language]}"
		else
			if !stream[:lang]
				stream[:lang] = guess_lang(title)
			end
		end
		stream[:title] = title
	end

	# チャプター名を決定
	pd[:chapters].each_with_index do |chapter, ix|
		title = $metadata[:chapter_name][ix]
		if !title
			$stdout.printf("チャプター #{ix+1} のタイトルが指定されていません\n")
		end
		chapter[:title] = title
	end

	# 出力するストリームの数を種類ごとに数える
	streams_v_output = pd[:streams_v].count { |s| s[:title] != "omit" }
	streams_a_output = pd[:streams_a].count { |s| s[:title] != "omit" }
	streams_s_output = pd[:streams_s].count { |s| s[:title] != "omit" }

	codec_count = {}
	# 対象VOB,IFOの決定 & ワークVOBの作成
	if $dryrun
		vobfile = pd[:vobfiles].first
	else
		vobfile = Tempfile.new(["dvd2mp4", ".vob"]).path

		if $simple_concat
			cmd = ["cat"]
			cmd += pd[:vobfiles]
			printf("Writing work VOB(simple)...\n")
			system(*cmd, out:vobfile)
			fail "#{$?}"  if $? != 0
			printf("...Complete.\n")
		else
			cmd1 = ["cat"]
			cmd1 += pd[:vobfiles]

			cmd2 = [FFMPEG_CMD]
			cmd2 += ["-hide_banner"]
			cmd2 += ["-loglevel", "error"]
			cmd2 += ["-analyzeduration", FF_ANALYZEDURATION]
			cmd2 += ["-probesize", FF_PROBESIZE]
			cmd2 += ["-y"]
			cmd2 += ["-i", "-"]
			cmd2 += ["-codec", "copy"]
			cmd2 += ["-map", "0", "-map", "-0:d"]
			cmd2 += ["-f", "vob"]
			cmd2 += [vobfile]

			printf("Writing work VOB...\n")
			Open3.pipeline(cmd1, cmd2)
			# fail "#{$?}"  if $? != 0
			printf("...Complete.\n")

			# 巻き直すとStream IDが変わるので調整
			pd[:streams_a].each do |stream|
				src_sid = stream[:id]
				codec_count[stream[:codec_name]] ||= 0
				case stream[:codec_name]
				when "ac3"
					new_sid = sprintf("0x%02x", 0x80 + codec_count["ac3"])
				when "dts"
					new_sid = sprintf("0x%02x", 0x88 + codec_count["dts"])
				else
					fail "想定外のオーディオコーデック : #{stream[:codec_name]}"
				end

				stream[:id] = new_sid

				codec_count[stream[:codec_name]] += 1
			end
		end
	end

	ifofile = pd[:ifofiles].first

	# 変換メインループ
	output_ranges.each do |output_range|
		start_sec = output_range.begin
		end_sec = output_range.end

		# チャプター情報ファイルを作成
		chapters_output = 0
		cfile = Tempfile.new(["chapter", ".txt"])
		cfile.printf(";FFMETADATA1\n")
		pd[:chapters].each.with_index(1) do |chapter, ix|
			next  if chapter[:title] == "omit"
			next  if chapter[:end] <= (start_sec + 0.5)
			next  if chapter[:start] >= (end_sec - 0.5)

			cfile.printf("[CHAPTER]\n")
			cfile.printf("TIMEBASE=1/1000000\n")
			cfile.printf("START=%d\n", chapter[:start] * 1000000)
			cfile.printf("END=%d\n", chapter[:end] * 1000000)
			cfile.printf("title=%s\n", chapter[:title] || "Chapter #{ix}")

			chapters_output += 1
		end
		cfile.flush
		system("cat", cfile.path)  if $dryrun

		# 変換コマンド生成
		cmd = [FFMPEG_CMD]
		cmd += ["-hide_banner"]
		cmd += ["-loglevel", "info"]
		cmd += ["-analyzeduration", FF_ANALYZEDURATION]
		cmd += ["-probesize", FF_PROBESIZE]
		cmd += ["-y"]  if $overwrite || $testmode
		cmd += ["-ifo_palette", ifofile]  if ifofile && (streams_s_output >= 1)
		cmd += ["-ss", start_sec.to_s]  if !$simple_concat
		cmd += ["-i", vobfile] # #0

		if chapters_output >= 2
			cmd += ["-ss", start_sec.to_s]  if !$simple_concat
			cmd += ["-i", cfile.path] # #1
			cmd += ["-map_chapters", "1"]
		end

		cmd += ["-ss", start_sec.to_s]  if $simple_concat
		cmd += ["-t", (end_sec - start_sec).to_s]
		cmd += ["-f", "mp4"]
		cmd += ["-movflags", "+faststart+disable_chpl"]
		cmd += ["-metadata", "album=#{$metadata[:album_name]}"]  if $metadata[:album_name]
		cmd += ["-metadata", "track=#{$metadata[:title_num]}"]  if $metadata[:title_num]
		cmd += ["-metadata", "title=#{$metadata[:title_name]}"]  if $metadata[:title_name]
		cmd += ["-metadata", "encoding_tool=#{$commandline}"]

		if streams_v_output >= 1
			filters_v = []

			cmd += ["-preset:v", $testmode ? "ultrafast" : "veryslow"]
			cmd += ["-tune:v", $video_tune]  if $video_tune
			cmd += ["-pix_fmt:v", "yuv420p"]
			cmd += ["-crf:v", $crf.to_s]
			if $quality_v == "l"
				cmd += ["-maxrate:v", "1.0M"]
				cmd += ["-bufsize:v", "2.5M"]
			end

			if $pullup24
				# 24fpsに変換
				if Rational(framerate).denominator == 1001
					framerate24 = "24000/1001"
				else
					framerate24 = "24"
				end

				filters_v << "fieldmatch"
				filters_v << "bwdif=mode=send_frame:deint=interlaced"
				filters_v << "fps=fps=#{framerate24}:round=#{$pullup24}"
			else
				# インターレース解除
				if $force_deinterlace || (vs1[:field_order] && vs1[:field_order] != "progressive")
					filters_v << ($testmode ? "bwdif=mode=send_frame" : "bwdif=mode=send_field")
				end
			end

			# ノイズ除去
			case $video_tune
			when "animation"
				filters_v << "hqdn3d"
			else
				filters_v << "vaguedenoiser"
			end

			# 黒レベル, 白レベル
			if $whitepoint || $blackpoint
				w = $whitepoint ? [$whitepoint[0] || 1, $whitepoint[1] || 1, $whitepoint[2] || 1] : [1,1,1]
				b = $blackpoint ? [$blackpoint[0] || 0, $blackpoint[1] || 0, $blackpoint[2] || 0] : [0,0,0]
				filters_v << "colorlevels=rimin=#{b[0]}:gimin=#{b[1]}:bimin=#{b[2]}:rimax=#{w[0]}:gimax=#{w[1]}:bimax=#{w[2]}"
			end

			# ガンマ, 彩度
			if $video_gamma || $video_saturation
				eq = []
				eq << "gamma=#{$video_gamma}"  if $video_gamma
				eq << "saturation=#{$video_saturation}"  if $video_saturation
				filters_v << "eq=#{eq.join(":")}"
			end

			# クリッピング
			if $video_crop
				in_w = vs1[:width]
				in_h = vs1[:height]
				crop_w = in_w - ($video_crop[2] + $video_crop[3])
				crop_h = in_h - ($video_crop[0] + $video_crop[1])
				crop_x = $video_crop[2]
				crop_y = $video_crop[0]
				out_w = in_w
				out_h = (crop_h > 360) ? in_h : 360
				filters_v << "crop=w=#{crop_w}:h=#{crop_h}:x=#{crop_x}:y=#{crop_y}:keep_aspect=1"
				filters_v << "scale=w=#{out_w}:h=#{out_h}"
			end

			# 回転
			case $video_rotate
			when 90
				filters_v << "transpose=clock"
			when 180
				filters_v << "hflip" << "vflip"
			when 270
				filters_v << "transpose=cclock"
			end

			# アスペクト比
			if $video_aspect
				filters_v << "setdar=#{$video_aspect.gsub(":", "/")}"
			end

			cmd += ["-filter:v", filters_v.join(",")]  if filters_v.size > 0
		end

		if streams_a_output >= 1
			if $flac_audio
				cmd += ["-codec:a", "flac", "-strict", "experimental"]
			else
				cmd += ["-codec:a", "libfdk_aac"]
				cmd += ["-profile:a", "aac_low"]

				case $quality_a
				when "h"
					cmd += ["-vbr:a", "5"]
				when "l"
					cmd += ["-vbr:a", "1"]
					cmd += ["-cutoff:a", "14000"]
				else
					cmd += ["-vbr:a", "3"]
					cmd += ["-cutoff:a", "18000"]
				end
			end
		end

		if streams_s_output >= 1
			cmd += ["-codec:s", "dvd_subtitle"]
		end

		# ストリーム毎のオプション指定
		scount = 0

		pd[:streams_v].each do |stream|
			next  if stream[:title] == "omit"

			cmd += ["-map", "##{stream[:id]}"]

			if streams_v_output >= 2
				cmd += ["-metadata:s:#{scount}", "language=#{stream[:lang]}"]
				cmd += ["-metadata:s:#{scount}", "title=#{stream[:title]}"]
				cmd += ["-metadata:s:#{scount}", "handler_name=#{stream[:title]}"]
			end

			scount += 1
		end

		pd[:streams_a].each do |stream|
			next  if stream[:title] == "omit"

			cmd += ["-map", "##{stream[:id]}"]

			# if streams_a_output >= 2
				cmd += ["-metadata:s:#{scount}", "language=#{stream[:lang]}"]
				cmd += ["-metadata:s:#{scount}", "title=#{stream[:title]}"]
				cmd += ["-metadata:s:#{scount}", "handler_name=#{stream[:title]}"]
			# end

			scount += 1
		end

		pd[:streams_s].each do |stream|
			next  if stream[:title] == "omit"

			cmd += ["-map", "##{stream[:id]}"]

			# if streams_s_output >= 2
				cmd += ["-metadata:s:#{scount}", "language=#{stream[:lang]}"]
				cmd += ["-metadata:s:#{scount}", "title=#{stream[:title]}"]
				cmd += ["-metadata:s:#{scount}", "handler_name=#{stream[:title]}"]
			# end

			scount += 1
		end

		# TODO:サムネイル画像

		if $dryrun
			cmd += [dst_basename + ".mp4"]
			p cmd
		else
			# ユニークな出力ファイル名を決定
			dst_filename = 1.step do |n|
				f = dst_basename + (n == 1 ? "" : " #{n}") + ".mp4"
				break f  if !File.exist?(f)
			end

			dst_filename2 = dst_filename
			cmd += [dst_filename2]
			system(*cmd)
			fail "#{$?}"  if $? != 0

			if File.exist?(dst_filename2)
				timestamp_src = (pd[:ifofiles] + pd[:vobfiles]).first
				File.utime(File.atime(timestamp_src), File.mtime(timestamp_src), dst_filename2)
#				File.rename(dst_filename2, dst_filename)
			end
		end
	end
end

def show_encoding_tool(filename)
	cmd = [FFPROBE_CMD]
	cmd += ["-hide_banner"]
	cmd += ["-loglevel", "warning"]
	cmd += ["-print_format", "json"]
	cmd += ["-show_format"]
	cmd += ["-i", filename]
	format = JSON.parse(Open3.capture3(*cmd)[0], symbolize_names:true)

	printf("%s\n", format[:format][:tags][:encoder])
end

def main(args)
	var_init
	$commandline = ProgName + " " + myShellwordsJoin(args)

	args.options do |opt|
		opt.banner = "#{ProgName} v#{Version} #{Copyright}\n" +
						"Usage: #{ProgName} [options] VTS_nn..."

		$probe = false
		opt.on("-p", "--[no-]probe",
			"ファイルの情報を表示する") do |v|
			$probe = v
		end

		$probe_raw = false
		opt.on("-r", "--[no-]probe-raw",
			"ファイルの情報を表示する(非編集)") do |v|
			$probe_raw = v
		end

		$start_pos = nil
		opt.on("-s", "--startpoint=pos", String,
			"開始位置を指定する(秒/時分秒/フレーム)") do |v|
			$start_pos = v
		end

		$end_pos = nil
		opt.on("-e", "--endpoint=pos", String,
			"終了位置を指定する") do |v|
			$end_pos = v
			$duration = nil
		end

		$duration = nil
		opt.on("-d", "--duration=dur", String,
			"出力する長さを指定する") do |v|
			$duration = v
			$end_pos = nil
		end

		$output_ranges = nil
		opt.on("--split-at=n,n-n,...", String,
			"出力する範囲を指定する") do |v|
			$output_ranges = v.split(",").map do |r|
				case r
				when /^(.*)-(.*)$/
					pos2sec($1, 30)
					pos2sec($2, 30)
					r
				else
					pos2sec(r, 30)
					r
				end
			end
		end

		$output_chapters = nil
		opt.on("--chapter=n,n-n,...", String,
			"出力するチャプターを指定する") do |v|
			$output_chapters = v.split(",").map do |c|
				case c
				when /^\s*(\d+)\s*$/
					$1.to_i-1
				when /^\s*(\d+)\s*-\s*(\d+)\s*$/
					($1.to_i-1) .. ($2.to_i-1)
				else
					nil
				end
			end
		end
		opt.on("--[no-]split-chapter",
			"チャプター毎に分割して出力する") do |v|
			$output_chapters = v ? [] : nil
		end

		$delete_chpt_sec = 0
		opt.on("--delete-short-chapter=n", Float,
			"n秒より短いチャプターを削除する") do |v|
			$delete_chpt_sec = (v<0) ? 0 : v
		end

		$chapter_offset = nil
		opt.on("--chapter-offset=n", String,
			"チャプターマークを全体的に移動する") do |v|
			$chapter_offset = v
		end

		$metadata[:album_name] = nil
		opt.on("--album-name=str", String,
			"アルバム名を指定") do |v|
			$metadata[:album_name] = v
		end

		$metadata[:title_num] = nil
		opt.on("--title-num=n", String,
			"タイトル番号を指定") do |v|
			$metadata[:title_num] = v
		end

		$metadata[:title_name] = nil
		opt.on("-t", "--title=str", String,
			"タイトルを指定") do |v|
			$metadata[:title_name] = v
		end

		$metadata[:s_video_name] = []
		opt.on("--title:v=str", String,
			"ビデオストリームのタイトルを指定('omit'で出力しない/'auto'で自動)") do |v|
			v = nil  if v == "auto"
			$metadata[:s_video_name] << v
		end

		$metadata[:s_audio_name] = []
		opt.on("--title:a=str", String,
			"オーディオストリームのタイトルを指定") do |v|
			v = nil  if v == "auto"
			$metadata[:s_audio_name] << v
		end

		$metadata[:s_subtitle_name] = []
		opt.on("--title:s=str", String,
			"字幕ストリームのタイトルを指定") do |v|
			v = nil  if v == "auto"
			$metadata[:s_subtitle_name] << v
		end

		$metadata[:chapter_name] = []
		opt.on("--title:c=str", String,
			"チャプタータイトルを指定") do |v|
			v = nil  if v == "auto"
			$metadata[:chapter_name] << v
		end

		$video_tune = nil
		opt.on("--tune:v=str", String,
			"ビデオの種類(film|animation|grain|stillimage...)") do |v|
			$video_tune = v
		end

		$pullup24 = nil
		opt.on("--pullup24[=round]", String,
			"24fps化する(near|up|down...)") do |v|
			$pullup24 = v || "near"
		end

		$force_deinterlace = nil
		opt.on("--[no-]force-deinterlace",
			"強制的にインターレース解除を行う/行わない") do |v|
			$force_deinterlace = v
		end

		$quality_v = nil
		$quality_a = nil
		opt.on("--hq",
			"高画質,高音質でエンコードする") do
			$quality_v = "h"
			$quality_a = "h"
		end
		opt.on("--hq:v",
			"高画質でエンコードする") do
			$quality_v = "h"
		end
		opt.on("--hq:a",
			"高音質でエンコードする") do
			$quality_a = "h"
		end
		opt.on("--lq",
			"低画質,低音質でエンコードする") do
			$quality_v = "l"
			$quality_a = "l"
		end
		opt.on("--lq:v",
			"低画質でエンコードする") do
			$quality_v = "l"
		end
		opt.on("--lq:a",
			"低音質でエンコードする") do
			$quality_a = "l"
		end

		$crf_base = nil
		$crf_offset = 0
		opt.on("--crf=n", String,
			"VBR画質を指定する(0:ロスレス - 21.0:デフォルト - 51:低|[+-]n)") do |v|
			if v =~ /^[+-]/
				$crf_offset = v.to_f
			else
				$crf_base = v.to_f
			end
		end

		$video_crop = nil
		opt.on("--crop=t,b,l,r", Array,
			"映像を切り取り(上,下,左,右)") do |v|
			$video_crop = v.map { |v| v.to_i }
		end

		$video_aspect = nil
		opt.on("--aspect=r", String,
			"映像のアスペクト比(w:h)") do |v|
			$video_aspect = v
		end

		$video_rotate = nil
		opt.on("--rotate=n", String, ["90", "180", "270"],
			"映像を回転(90|180|270)") do |v|
			$video_rotate = v.to_i
		end

		$whitepoint = nil
		opt.on("--white-point=r,g,b", Array,
			"映像のホワイトポイント(0～255)") do |v|
			$whitepoint = v.map { |v| v.to_i / 255.0 }
		end

		$blackpoint = nil
		opt.on("--black-point=r,g,b", Array,
			"映像のブラックポイント(0～255)") do |v|
			$blackpoint = v.map { |v| v.to_i / 255.0 }
		end

		$video_gamma = nil
		opt.on("--gamma=n", Float,
			"映像のガンマ補正(0.1〜1(デフォルト)〜10)") do |v|
			$video_gamma = v
		end

		$video_saturation = nil
		opt.on("--saturation=n", Float,
			"映像の彩度補正(0〜1(デフォルト)〜3.0)") do |v|
			$video_saturation = v
		end

		$flac_audio = false
		opt.on("-y", "--[no-]flacaudio",
			"音声をFLAC(可逆圧縮)でエンコードする") do |v|
			$flac_audio = v
		end

		$adjust_fps = true
		# opt.on("--[no-]adjust-fps",
		# 	"チャプター時間のfpsの調整を行う") do |v|
		# 	$adjust_fps = v
		# end

		$strict_length = false
		# opt.on("--[no-]strict-length",
		# 	"再生時間を厳密に測定する") do |v|
		# 	$strict_length = v
		# end

		$simple_concat = false
		opt.on("--[no-]simple-concat",
			"VOBファイルを単純結合する") do |v|
			$simple_concat = v
		end

		$overwrite = false
		opt.on("-y", "--[no-]overwrite",
			"出力ファイルが既に存在しても上書きする") do |v|
			$overwrite = v
		end

		$testmode = false
		opt.on("--[no-]testmode",
			"テストモード(高速,低画質)") do |v|
			$testmode = v
		end

		$dryrun = false
		opt.on("--[no-]dry-run",
			"変換処理を実際には行わない") do |v|
			$dryrun = v
		end

		$show_encoder = false
		opt.on("--[no-]show-encoder",
			"エンコーダ情報を表示") do |v|
			$show_encoder = v
		end

		opt.parse!

		if $flac_audio
			$quality_a = nil
		end

		if !$crf_base
			case $quality_v
			when "h"
				$crf_base = 19.0
			when "l"
				$crf_base = 23.0
			else
				$crf_base = 21.0
			end
		end

		if $testmode
			$crf_base = 26.0
			$flac_audio = false
			$quality_v = "l"
			$quality_a = "l"
		end

		$crf = ($crf_base + $crf_offset).clamp(0.0, 51.0)

		if args.empty?
			if $probe_raw
				pp probe_disc_data_raw
			elsif $probe
				probe_disc
			else
				print(opt.help)
			end
		else
			args.each do |arg|
				if $show_encoder
					show_encoding_tool(arg)
				else
					vts_num = vts_num_to_i(arg)
					if $probe_raw
						pp probe_vts_data_raw(vts_num)
					elsif $probe
						probe_vts(vts_num)
					else
						dvd2mp4(vts_num)
					end
				end
			end
		end
	end

	return $rcode
end

exit main(ARGV)
